name: "Unentropy Find Database"
description: "Find and download the latest metrics database artifact"
author: "Unentropy Team"
branding:
  icon: "download"
  color: "orange"

inputs:
  database-artifact:
    description: "Name of artifact to search for"
    required: false
    default: "unentropy-metrics"
  database-path:
    description: "Local path where database should be placed"
    required: false
    default: "./unentropy-metrics.db"
  branch-filter:
    description: "Branch to search for previous runs"
    required: false
    default: "${{ github.ref_name }}"

outputs:
  database-found:
    description: "Whether a previous database was found and downloaded"
  database-path:
    description: "Path to the database file (may not exist if not found)"
  source-run-id:
    description: "ID of the workflow run where database was found"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "1.2"
    - name: Find and download database
      id: find-db
      shell: bash
      run: |
        # Create temp file for outputs
        OUTPUT_FILE=$(mktemp)

        # Run the Node.js script with output file
        bun "${{ github.action_path }}/dist/find-database.js" "$OUTPUT_FILE"

        # Read outputs from file and set them
        if [ -f "$OUTPUT_FILE" ]; then
          echo "Output file contents:" >&2
          cat "$OUTPUT_FILE" >&2
          while IFS='=' read -r key value; do
            echo "Setting output: $key=$value" >&2
            echo "$key=$value" >> $GITHUB_OUTPUT
          done < "$OUTPUT_FILE"
          rm "$OUTPUT_FILE"
        else
          echo "Output file not found: $OUTPUT_FILE" >&2
        fi
      env:
        INPUT_DATABASE_ARTIFACT: ${{ inputs.database-artifact }}
        INPUT_DATABASE_PATH: ${{ inputs.database-path }}
        INPUT_BRANCH_FILTER: ${{ inputs.branch-filter }}
        GITHUB_TOKEN: ${{ github.token }}
