export function Footer() {
  return (
    <footer class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 mt-8 border-t border-gray-200 dark:border-gray-700">
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between text-sm text-gray-600 dark:text-gray-400">
        <div>
          Generated by <span class="font-semibold">Unentropy</span> v0.1.0
        </div>
        <div class="mt-2 sm:mt-0">
          <a
            href="https://github.com/unentropy/unentropy"
            class="hover:text-gray-900 dark:hover:text-white"
          >
            View Documentation
          </a>
        </div>
      </div>
    </footer>
  );
}
