name: "Unentropy Generate Report"
description: "Generate HTML report from collected metrics"
author: "Unentropy Team"
branding:
  icon: "file-text"
  color: "green"

inputs:
  database-path:
    description: "Path to local database file"
    required: false
    default: "./unentropy-metrics.db"
  database-artifact:
    description: "Name of artifact containing database (fallback if database-path doesn't exist)"
    required: false
    default: "unentropy-metrics"
  output-path:
    description: "Output path for generated HTML report"
    required: false
    default: "./unentropy-report.html"
  time-range:
    description: 'Time range filter (e.g., "last-30-days", "all")'
    required: false
    default: "all"
  title:
    description: "Report title"
    required: false
    default: "Metrics Report"

outputs:
  report-path:
    description: "Path to generated HTML report"
  metrics-count:
    description: "Number of metrics included in report"
  data-points:
    description: "Total number of data points in report"
  time-range-start:
    description: "ISO 8601 timestamp of oldest data point"
  time-range-end:
    description: "ISO 8601 timestamp of newest data point"

runs:
  using: "composite"
  steps:
    - name: Run report generation
      shell: bash
      run: node "${{ github.action_path }}/dist/report.node.js"
      env:
        INPUT_DATABASE_PATH: ${{ inputs.database-path }}
        INPUT_DATABASE_ARTIFACT: ${{ inputs.database-artifact }}
        INPUT_OUTPUT_PATH: ${{ inputs.output-path }}
        INPUT_TIME_RANGE: ${{ inputs.time-range }}
        INPUT_TITLE: ${{ inputs.title }}
