name: "Unentropy Generate Report"
description: "Generate HTML report from collected metrics"
author: "Unentropy Team"
branding:
  icon: "file-text"
  color: "green"

inputs:
  database-artifact:
    description: "Name of artifact containing database"
    required: false
    default: "unentropy-metrics"
  output-path:
    description: "Output path for generated HTML report"
    required: false
    default: "./unentropy-report.html"
  time-range:
    description: 'Time range filter (e.g., "last-30-days", "all")'
    required: false
    default: "all"
  title:
    description: "Report title"
    required: false
    default: "Metrics Report"

outputs:
  report-path:
    description: "Path to generated HTML report"
  metrics-count:
    description: "Number of metrics included in report"
  data-points:
    description: "Total number of data points in report"
  time-range-start:
    description: "ISO 8601 timestamp of oldest data point"
  time-range-end:
    description: "ISO 8601 timestamp of newest data point"

runs:
  using: "node20"
  main: "dist/report.js"
