name: "Unentropy Generate Report"
description: "Generate HTML report from collected metrics"
author: "Unentropy Team"
branding:
  icon: "file-text"
  color: "green"

inputs:
  database-path:
    description: "Path to local database file (should be provided by find-database action)"
    required: true
  output-path:
    description: "Output path for generated HTML report"
    required: false
    default: "./unentropy-report.html"
  time-range:
    description: 'Time range filter (e.g., "last-30-days", "all")'
    required: false
    default: "all"
  title:
    description: "Report title"
    required: false
    default: "Metrics Report"
  config-path:
    description: "Path to unentropy.json configuration file"
    required: false
    default: "./unentropy.json"

outputs:
  report-path:
    description: "Path to generated HTML report"
  metrics-count:
    description: "Number of metrics included in report"
  data-points:
    description: "Total number of data points in report"
  time-range-start:
    description: "ISO 8601 timestamp of oldest data point"
  time-range-end:
    description: "ISO 8601 timestamp of newest data point"

runs:
  using: "composite"
  steps:
    - name: Run report generation
      id: report
      shell: bash
      run: |
        # Run the Node.js script and capture outputs
        node "${{ github.action_path }}/dist/report.node.js"

        # Read the outputs from environment variables set by the script
        echo "report-path=${REPORT_PATH:-./unentropy-report.html}" >> $GITHUB_OUTPUT
        echo "metrics-count=${METRICS_COUNT:-0}" >> $GITHUB_OUTPUT
        echo "data-points=${DATA_POINTS:-0}" >> $GITHUB_OUTPUT
        echo "time-range-start=${TIME_RANGE_START:-}" >> $GITHUB_OUTPUT
        echo "time-range-end=${TIME_RANGE_END:-}" >> $GITHUB_OUTPUT
      env:
        INPUT_DATABASE_PATH: ${{ inputs.database-path }}
        INPUT_OUTPUT_PATH: ${{ inputs.output-path }}
        INPUT_TIME_RANGE: ${{ inputs.time-range }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_CONFIG_PATH: ${{ inputs.config-path }}
