name: "Unentropy Collect Metrics"
description: "Collect custom code metrics and store in SQLite database"
author: "Unentropy Team"
branding:
  icon: "bar-chart-2"
  color: "blue"

inputs:
  config-path:
    description: "Path to unentropy.json configuration file"
    required: false
    default: "./unentropy.json"
  database-path:
    description: "Path where database file is stored locally (should be provided by find-database action)"
    required: true
  continue-on-error:
    description: "Continue workflow if metric collection fails"
    required: false
    default: "true"

outputs:
  metrics-collected:
    description: "Count of successfully collected metrics"
  metrics-failed:
    description: "Count of metrics that failed to collect"
  database-path:
    description: "Path to the database file that was created/updated"
  build-id:
    description: "Database ID of the build context record created"

runs:
  using: "composite"
  steps:
    - name: Run metrics collection
      id: collect
      shell: bash
      run: |
        # Run the Node.js script and capture outputs
        node "${{ github.action_path }}/dist/collect.node.js"

        # Read the outputs from environment variables set by the script
        echo "metrics-collected=${METRICS_COLLECTED:-0}" >> $GITHUB_OUTPUT
        echo "metrics-failed=${METRICS_FAILED:-0}" >> $GITHUB_OUTPUT
        echo "database-path=${DATABASE_PATH:-./unentropy-metrics.db}" >> $GITHUB_OUTPUT
        echo "build-id=${BUILD_ID:-}" >> $GITHUB_OUTPUT
      env:
        INPUT_CONFIG_PATH: ${{ inputs.config-path }}
        INPUT_DATABASE_PATH: ${{ inputs.database-path }}
        INPUT_CONTINUE_ON_ERROR: ${{ inputs.continue-on-error }}
